---
name: Test

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "**/requirements_dev.txt"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
      - name: Prepare allenporter/home-assistant-synthetic-home
        uses: actions/checkout@v4
        with:
          repository: allenporter/home-assistant-synthetic-home
          path: home-assistant-synthetic-home
          sparse-checkout: |
            custom_components
      - name: Test with pytest
        run: |
          export PYTHONPATH="${PYTHONPATH}:./home-assistant-synthetic-home/"
          pytest
